services:
  - type: web_service
    name: rep-main-php
    env: docker
    branch: main
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /index.php
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_USER
        value: ALPHA
      - key: DB_PASS
        value: 12369874
      - key: DB_NAME
        value: PruebaAlpha
